### ISSUE TITLE
Support enum flags

### ISSUE THREAD

**Issue by Entomy** [Entomy/libAnne#10]
Enumerations in Ada are a joke, barely useful for anything compared to most other languages. This is largely because on of the more sophisticated uses of enumerations , bitflags, is not possible because of what I consider a massive oversight: bitwise operators are only defined for modular types.

I strongly feel C# does the right thing by implementing enumerations as exclusive values by default, but also providing the [`[Flags]`](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute) attribute.

libAnne should support something similar to this.

**Comment by ytomino** [comment]
Hello. 
Are bit-wise operations for enum meaningful?
The set type has been used for this purpose in the Pascal-like languages with history.
Pascal-like set type under Ada is introduced as `array(any-discrete-type) of Boolean`, that has predefined "and", "or", "xor", "not".
http://ada-auth.org/standards/rm12_w_tc1/html/RM-4-5-1.html
If you are worried about efficiency, gcc can optimize them with `pragma Pack`.
C#'s enum is danger compared with the set type because it's easy to be mistaken.
Of course, some kinds of packed integers are needed to satisfy the compatibility to foreign-call, but should be closed into the interop layers.

By the way, there are `'Enum_Rep` and `'Enum_Val` those are the implementation-defined attributes of GNAT, but ratified in Ada 202x.
The uses of branching by Size and Address clauses like 2b36a560 are unneeded.
http://ada-auth.org/standards/2xrm/html/RM-13-4.html

Excuse for my pushiness.

**Comment by Entomy** [comment]
> Are bit-wise operations for enum meaningful?

Is for interfacing with C. Purely Ada code should avoid it.

> C#'s enum is danger compared with the set type because it's easy to be mistaken.

Danger to be mistaken? How so?

> The uses of branching by Size and Address clauses like 2b36a56 are unneeded.

Trying to `and` integers of different sizes will quickly reveal why this was necessary. If the view type is 32 bits and is overlayed on a 64 bit type, only 32 bits will be modified. Conversely, if the view type is 32 bits and is overlayed on an 8 bit type, 24 additional bits will be modified, effectively overrunning, which is a dangerous situation.

**Comment by Entomy** [comment]
>By the way, there are 'Enum_Rep and 'Enum_Val those are the implementation-defined attributes of GNAT, but ratified in Ada 202x.

That doesn't help anyone until Ada 202x is finalized and implemented. And even then it doesn't help situations where I need to `CreateFileW` with both `Normal` and `Compressed` attributes set.

**Comment by Entomy** [comment]
~~~~ ada
type File_Attributes_And_Flags is array(Natural range 0 .. 31) of Boolean;

None : constant File_Attributes_And_Flags := (others => False);
Readonly : constant File_Attributes_And_Flags := (0 => True, others => False);
Hidden : constant File_Attribute_And_Flags := (1 => True, others => False);
System : constant File_Attribute_And_Flags := (2 => True, others => False);
Directory : constant File_Attribute_And_Flags := (3 => True, others => False):
-- This gets old extremely fast, and is very hard to parse for typos
~~~~

versus:

![image](https://user-images.githubusercontent.com/25399505/61731493-983f1680-ad49-11e9-9a3e-95c2abb4a9f4.png)

Also happens to be much easier to compare against the header files it maps to:

![image](https://user-images.githubusercontent.com/25399505/61731556-befd4d00-ad49-11e9-8a0f-506c48419b34.png)

And when the end result for both is just: 

~~~~ ada
Hidden and System
~~~~

I'm going with the approach that's easier to maintain, unless a serious problem can be found with it.

**Comment by ytomino** [comment]
Thanks for your replying.

>Is for interfacing with C. Purely Ada code should avoid it.

I see.

>That doesn't help anyone until Ada 202x is finalized and implemented. 

`'Enum_Rep` and '`Enum_Val' are implemented in gcc/GNAT since a long time ago. These are GNAT's implementation-defined attributes in the first place.

> And even then it doesn't help situations where I need to CreateFileW with both Normal and Compressed attributes set.

??

For example:

````
type One_File_Attribute_And_Flag is (Readonly, Hiden, System, Directory, ...); -- 0, 1, 2, 3...
type File_Attributes_And_Flags is array(One_File_Attribute_And_Flag) of Boolean;
pragma Pack (File_Attributes_And_Flags);
````

This is good enough.

**Comment by ytomino** [comment]
Or, the Enum_Rep version.

type File_Attributes_And_Flags  is [yours](https://github.com/Entomy/libAnne/blob/master/Windows/Bindings.winnt.ads);

```
CreateFileW (...,
  dwFlagsAndAttributes =>
    File_Attributes_And_Flags'Enum_Rep (Hidden) or File_Attributes_And_Flags'Enum_Rep (System), 
    ...);
```

In either case, I feel that is exaggeratedly to making the public generic package.

**Comment by Entomy** [comment]
>'Enum_Rep and 'Enum_Val are implemented in gcc/GNAT since a long time ago. These are GNAT's implementation-defined attributes in the first place.

I'm trying to keep the library compiler-agnostic, so any compiler specific features should be avoided, and I've been working on removing them as time goes on.

> ??

Those attributes do not do anything for helping me combine flags. And I don't need Ada to get the representation value, since passing the result to C works just fine. I can implement the entire thing without those attributes.

> This is good enough.

That's an interesting way to put it.

~~~~ ada
with Ada.Text_IO;
use Ada.Text_IO;

procedure Scratch is
	type One_File_Attribute_And_Flag is (None, Readonly, Hidden, System, Directory);
	type File_Attributes_And_Flags is array(One_File_Attribute_And_Flag) of Boolean with Pack, Size => 32;
	
	type View_Type is mod 2**32;
	
	Result : File_Attributes_And_Flags;
	View : View_Type;
	for View'Address use Result'Address;
begin
	Result(Hidden) := True;
	Result(System) := True; --This gets increasingly verbose as more flags need to be set.
	Put_Line("Value: " & View_Type'Image(View));
end Scratch;
~~~~

Whereas with my approach:
~~~~ ada
with Generics.Discrete_Bitwise, Ada.Text_IO;
use Generics.Discrete_Bitwise, Ada.Text_IO;

procedure Scratch is
	type File_Attribute_And_Flag is (None, Readonly, Hidden, System, Directory);
	for File_Attribute_And_Flags use (
		None => 0,
		Readonly => 1,
		Hidden => 2,
		System => 4,
		Directory => 8);
		
	function "not" is new Generics.Discrete_Bitwise.Discrete_Not(Name);
	function "and" is new Generics.Discrete_Bitwise.Discrete_And(Name);
	function "or" is new Generics.Discrete_Bitwise.Discrete_Or(Name);
	function "xor" is new Generics.Discrete_Bitwise.Discrete_XOr(Name);
	
	type View_Type is mod 2**32;
	
	Result : File_Attributes_And_Flags := Hidden and True; --We can now even make this constant if desired (it often is)
	View : View_Type;
	for View'Address use Result'Address;
begin
	Put_Line("Value: " & View_Type'Image(View));
end Scratch;
~~~~

> In either case, I feel that is exaggeratedly to making the public generic package.

Well in that case we can discuss whether it should be a public interface of the SAL. But regardless, this is the better solution. It solves issues like needing to make the named value constant.

**Comment by Entomy** [comment]
> Or, the Enum_Rep version.
> type File_Attributes_And_Flags  is yours;
> CreateFileW (...,
>   dwFlagsAndAttributes =>
>     File_Attributes_And_Flags'Enum_Rep (Hidden) or File_Attributes_And_Flags'Enum_Rep (System), 
>     ...);
> 
> In either case, I feel that is exaggeratedly to making the public generic package.

Dear god, seriously? This is your idea of "good enough"?
That same example using my approach:

~~~~ ada
CreateFileW(..., dwFlagsAndAttributes => Hidden or System, ...)
~~~~

**Comment by Entomy** [comment]
Furthermore, per [13.2](http://ada-auth.org/standards/12aarm/html/AA-13-2.html) packing to a specific size is not a hard requirement, merely a suggestion on the same level as Inline. This makes the approach you described vulnerable to architectural and compiler differences, whereas I'm using an overlay of the specific size. If you try your approach on a system where packing is not possible you can easily get a situation where 8**32 bits are now allocated, operated upon, and then attempted to be passed around to things not expecting such a massive datastructure.

**Comment by ytomino** [comment]
About the set.

>	Result(Hidden) := True;
>	Result(System) := True; --This gets increasingly verbose as more flags need to be set.

Of course, it can be into one-line.

````
Result : File_Attributes_And_Flags := (Hidden | System => True, others => False);
````

>I'm trying to keep the library compiler-agnostic, so any compiler specific features should be avoided, and I've been working on removing them as time goes on.

I'm sorry for my misunderstanding.
I thought you are targeting to gcc/GNAT, because some descriptions of https://github.com/Entomy/libAnne/wiki/Binding-Conventions are only acceptable in GNAT.

>If you try your approach on a system where packing is not possible you can easily get a situation where 8**32 bits are now allocated, operated upon, and then attempted to be passed around to things not expecting such a massive datastructure.

 If you say that, the using representation including the formal type's Size in the generic package is compiler-depended, strictly speaking.
Both of the template model (like C++, GNAT is this) and the shared-code model (like ML) are assumed in RM.
http://ada-auth.org/standards/aarm12_w_tc1/html/AA-12-3.html

>Dear god, seriously? This is your idea of "good enough"?

Just limited for interop used only in one place, I think the effect of decreasing the lines including the declarations. 
Ah, you are right in general. `'Enum_Rep` is classified as workaround for the case of that the declaration cannot be rewritten. I should not recommend it to other person.

**Comment by Entomy** [comment]
> I thought you are targeting to gcc/GNAT, because some descriptions of https://github.com/Entomy/libAnne/wiki/Binding-Conventions are only acceptable in GNAT.

Such as? I unfortunantly don't have any other Ada compilers to test this with.

> If you say that, the using representation including the formal type's Size in the generic package is compiler-depended, strictly speaking.
Both of the template model (like C++, GNAT is this) and the shared-code model (like ML) are assumed in RM.
http://ada-auth.org/standards/aarm12_w_tc1/html/AA-12-3.html

I'm not sure what you are trying to say here.

> Just limited for interop used only in one place, I think the effect of decreasing the lines including the declarations.

If I understand this correctly, I have to disagree. While your approach winds up with slightly less lines of code, mine results in considerably less typed characters, and can for the most part be made into a snippet.

**Comment by ytomino** [comment]
>Such as? 

In general, Ada's standard types do not correspond to C's types. Using `Interfaces.C` or adding `with Convention => C` is needed.
Especially, Ada's unconstrained array can not be passed to C's functions directly, like: 

https://github.com/Entomy/libAnne/blob/master/Common/Bindings.stdio.ads
```
function fgets(str : String; num : Integer; stream : Address) return String with Import, Convention => C;
```

GNAT can handle to pass the unconstrained array. It's permitted in http://ada-auth.org/standards/2xrm/html/RM-B-3.html , but *need not support*.

>I'm not sure what you are trying to say here.

If the compiler has adopted the shared-code model for generic, generic do not behave like template. All instances share one code. All integers are migrated to one common type with the range information. The representations are lost in such generic packages.
So some tricks like `Generics.Discrete_Bitwise` will not work probably. (Sorry, I'm not confident)

If you do not care about the these incompatibility, you do not need to care about `pragma Pack`.

>I unfortunantly don't have any other Ada compilers to test this with.
Me too.
However, Mr. Randy sometimes talks about Janus/Ada  in comp.lang.ada.
He mentioned that Janus/Ada is the shared-code model.

Again, Thanks and excuse me for talking a barren argument... that has been prolonged unexpectedly.

**Comment by Entomy** [comment]
> In general, Ada's standard types do not correspond to C's types.

Source?

I know they aren't required to, but I've been under the impression that in practice they always do. If this winds up being wrong I can make the necessary adjustments.

> Especially, Ada's unconstrained array can not be passed to C's functions directly

> GNAT can handle to pass the unconstrained array. It's permitted in http://ada-auth.org/standards/2xrm/html/RM-B-3.html , but need not support.

I do admit in the bindings documentation that I am surprised this works. I will change this if found on any given platform or compiler this does not work.

> If the compiler has adopted the shared-code model for generic, generic do not behave like template. All instances share one code.

I'm aware of this part and find it acceptable as an optimizer is likely to catch it anyways

> All integers are migrated to one common type with the range information. The representations are lost in such generic packages.

I'm not sure where you're getting this though. In a very strict pedantic sense yes the representation is lost, and that's because it's not actually used (since it's a view overlay this is actually expected behavior).

> So some tricks like `Generics.Discrete_Bitwise`

It's not much of a trick, as can be seen [here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtQn0nSBnVAV2LJMIAOQBaMQGoAKgjzdJAB2JNgAWyaSA7ngYNJxTGtQA3TJIIJzWpsRZ42S4hj5D0kgEYBPC1clYAMyY%2BBgJJAFIABgBBCUkAYWxJAN1MFiY1c1Z3S3NlVDcBc3TM/zwAgMxiB2BSKNipbkxzEEkEAgJFbhAAeh7gZGQAOmAWPiGSYB7UFgYHTHQC7n7BsQAOIYAmIcj%2B9IIAfWI1HoAFFXUmMQBlfkFMA8jIgFYAgDFUx5eAgDkMzCG7TUDHCmwAzOdVBobnchF9Xh8GA8nq8/pl6sooZpbgI4YiHmjzBBrgBHPi2TCkSQAIQwXgO%2BIOhIiYIAIuEwUlQZtMAAPDKKJFDDgebkASg51Pq9Ti0i8inMXjukjQWDaVUpkhIkgYqA4klYkj5AqFGOchUMkmw/LUgvM8nqkidkmAaSqeGQjud3oI8vMrPkyEMBAecoVknkkggHPiHOwErBUpi3oCfBYyAIeBmkgD3CDmBDBwA8sQIAAZTABAhUgBKeGA7UkrVz%2BcLYcwYoMBYELBzgeDob9kulMSiAE5U%2BnM9mWwPi6WK1Xa/XG83%2BwXBwrO8Ge3283P2xHuCOx%2BOa5huCEwmv9xuDu3h6PImOPJhgA4T%2BPynvW5vMGARGuPAAC9zDjDlWUkAA2AAWXw0k/Z9xywZBmEMRDTyQ59fXDABZFw0PvP0j0kYx3E2AAqCjYMfaIMPHcdF0OAA1PBMC0JtJHw9AQlsIiFVohisMwidtSYg5WPYgDonQdBDG4BQ%2BCaSQmOk2T5OPRMRzo4ShLHOsGxYtiONabjeOIfjMEE3ThICbUDPaCTjLUuSL0U5SHIIFyNOsnSRL089L1CJz2M4szCIfLSn382z7IvK8Qq0by3MkJTzECq9koU6yYpfN8P2ivSz3i4LJJMiCVMrIzQvsldqq0HK9LSdBGufTAGG4b9ZzvdsAKA0CWWwCqwU2eCWHo58ULQqzCpssccPMcK%2BMPSMyMkSiKLWXyiuE8SyrCgjlqHKK/J20TiEqqtEqy9zzFUkQZNc7KTomkTPMSg6eIi46k1Oua7Iu96ypu1KPLqm7trm4qgvqz7zMs1rcoByQMtK5yHvUlK0pRkqvIxp7NN%2Bs7X3fcbZty1HYZACq9uMrVAbqxLEfHZrEfazqAh/A8/T6kCwM5CraCgsbXqmilXvHBauMOiyVoUNaNq2l7yb02nQtMmWEeV3Lx2RtWkvxjTQbuqqIeVv6KcZ/aNa%2Bo6BO1s7kaB9HHqN7HPLNomVeEymPpt%2BHIq9nXnyd3HrsNrGPNxz3XpJgqLYCsPrZpqqPtqwymYd4TWazsd2ZmhPJswVDxe9kSpaW2XiNWjB1qopWvcLkT9bh777aDx2xNT4GI4U43Lrx123Mh4P9Ktun/bbqzc70p3x6k3vbpR8HF5Hs7fet6Xbar9uJZDuKYfDoe%2B/d6PV5n5847JpvoYS5O2QHtOGYzsrmbalgWtz5qIwCRGdzsHGMMcrf26oWEsvkfTEWkCoCoHoDhljqiRCA550BUgAJrtV1FoKkABxQwaQEy/RTNqaBTBYHIHgYg7G0ZkzemdCglk7JOSSHoF6OhkgMF6FQBxCCcZ1p1FoewvBzRey8OYTBQh2kUxpgzFmURmxNgkG5CRFgoVQEPBLBAUh5DKGGUkYIiIBiEGGU4tolIFDjHtFolfNhKlEHUwfpwrB9NJDCIQidb%2B1oTTT0bnEGSmhNiRFoKNJgHVUBOFMHgLAChrTKDcnIyQbwZHThYMeGIcQIDtE6L0HoWg8nCk4GIYIlgJjECmNwAg2RbDoGWME44PQgQMB6DWXCYgoLrEBAQYEEp0lSCYAoTQ3AEAkDCAgbIyRtSTlkTMBQWhhnKQ8HSFUMz5AEAUKgTmmgZSNBqEiLsBBdwVKYCGTILACBDEkAACW4ZgMwF1cg%2BGQKwFgqAwivmNu4fpBptnLNtHMJ5KTUr2HOT8qZgLSTkkMBAMYahOIAEkzlviqNubsACEUhldBdSM0K%2BBqCopsfR0QRBikYKIZ4IhSAsFEJEClqBRD%2BMkLwXEYFwS0ApQQalxKSUAGsQDPEiKSkQMEKVUpEDS0gdKRAUu6AKjlYriWkDgLAJAaBbSpDIBQCAqrFDqpAKMY53B0hdGGdWFIoQqjdAgB4TlpAPAOFsF4UQbLSCqtOQQIssxHXytIFgDQbAkQ2vwIYWRZhujer5MXPgIYnUUocCGBgNq5geBUMQLw8QMDCBEM6gg1Q1AxpJcwNgIAOBcCTd0SAJLUCKBSWG6VsJhC0ALWSkVNrJW8jWO02CLp9hRhzWmblnYIC4EINqUEYJ6AJFQGqpEF0x2NskP49lnKxQ8r5QKhNQqW3esldKkAsrl1NpEJsLd4qd2kDlTSldpA7mdRmCAGCQA%3D%3D%3D). It's literally just selecting the correct size overlay so that the correct assembler sizes can be used. It looks far more sophisticated than it really is because of limitations in Ada. This isn't some kind of sorcery. You can see it select a different branch based on the size [here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtQn0nSBnVAV2LJMIAOQBaMQGoAKgjzdJAB2JNgAWyaSA7ngYNJxTGtQA3TJIIJzWpsRZ42S4hj5D0kgEYBPC1clYAMyY%2BBgJJAFIABgBBCUkAYWxJAN1MFiY1c1Z3S3NlVDcBc3TM/zwAgMxiB2BSKNipbkxzEEkEAgJFbhAAeh7gZGQAOmAWPiGSYB7UFgYHTHQC7n7BsQAOIYAmIcj%2B9IIAfWI1HoAFFXUmMQBlfkFMA8jIgFYAgDFUx5eAgDkMzCG7TUDHCmwAzOdVBobnchF9Xh8GA8nq8/pl6sooZpbgI4YiHmjzBBrgBHPi2TCkSQAIQwXgO%2BIOhIiYIAIuEwUlQZtMAAPDKKJFDDgebkASg51Pq9Ti0i8inMXjukjQWDaVUpkhIkgYqA4klYkj5AqFGOchUMkmw/LUgvM8nqkidkmAaSqeGQjud3oI8vMrPkyEMBAecoVknkkggHPiHOwErBUpi3oCfBYyAIeBmkgD3CDmBDBwA8sQIAAZTABAhUgBKeGA7UkrVz%2BcLYcwYoMBYELBzgeDob9kulMSiAE5U%2BnM9mWwPi6WK1Xa/XG83%2BwXBwrO8Ge3283P2xHuCOx%2BOa5huCEwmv9xuDu3h6PImOPJhgA4T%2BPynvW5vMGARGuPAAC9zDjDlWUkAA2AAWXw0k/Z9xywZBmEMRDTyQ59fXDABZFw0PvP0j0kYx3E2AAqCjYMfaIMPHcdF0OAA1PBMC0JtJHw9AQlsIiFVohisMwidtSYg5WPYgDonQdBDG4BQ%2BCaSQmOk2T5OPRMRzo4ShLHOsGxYtiONabjeOIfjMEE3ThICbUDPaCTjLUuSL0U5SHIIFyNOsnSRL089L1CJz2M4szCIfLSn382z7IvK8Qq0by3MkJTzECq9koU6yYpfN8P2ivSz3i4LJJMiCVMrIzQvsldqq0HK9LSdBGufTAGG4b9ZzvdsAKA0CWWwCqwU2eCWHo58ULQqzCpssccPMcK%2BMPSMyMkSiKLWXyiuE8SyrCgjlqHKK/J20TiEqqtEqy9zzFUkQZNc7KTomkTPMSg6eIi46k1Oua7Iu96ypu1KPLqm7trm4qgvqz7zMs1rcoByQMtK5yHvUlK0pRkqvIxp7NN%2Bs7X3fcbZty1HYZACq9uMrVAbqxLEfHZrEfazqAh/A8/T6kCwM5CraCgsbXqmilXvHBauMOiyVoUNaNq2l7yb02nQtMmWEeV3Lx2RtWkvxjTQbuqqIeVv6KcZ/aNa%2Bo6BO1s7kaB9HHqN7HPLNomVeEymPpt%2BHIq9nXnyd3HrsNrGPNxz3XpJgqLYCsPrZpqqPtqwymYd4TWazsd2ZmhPJswVDxe9kSpaW2XiNWjB1qopWvcLkT9bh777aDx2xNT4GI4U43Lrx123Mh4P9Ktun/bbqzc70p3x6k3vbpR8HF5Hs7fet6Xbar9uJZDuKYfDoe%2B/d6PV5n5847JpvoYS5O2QHtOGYzsrmbalgWtz5qIwCRGdzsHGMMcrf26oWEsvkfTEWkCoCoHoDhljqiRCA550BUgAJrtV1FoKkABxQwaROw6EsJIfq/N2SckkCNWiKZtTQKYLA5A8DEHY2jMmb0zoUEsnIUkegXp2GSAwXoVAHEIJxnWnUNh/C8HNF7KIihMEEyNxTGmDMWZZGbE2CQbkJEWChVAQ8EsEA6EMKYYZRRfCIiSJUog1oxiUiMIQYZWiV8LGONXBVQRWD6aSGkQhE639rQmmno3OIMlNCbEiLQUaTAOqoCcKYPAWAFDWmUG5NRkg3gqOnCwY8MQ4gQHaJ0XoPQtClOFJwMQwRLATGIFMbgBBsi2HQMsKJxwehAgYD0GsuExBQXWICAgwIJR5KkEwBQmhuAIBIGEBA2RkjaknKomYCgtBTOUh4OkKplnyAIAoVAnNNAykaDUJEXYCC7nqUwEMmQWAECGJIAAEsIzAZgLq5B8MgVgLBUBhFfMbdwYyDRHK2baOYnzsmpXsHc4FiyIWknJIYCAYw1CcQAJK3LfFUbc3YAHopDK6C6kYkV8DUFRTY5iYgiDFIwUQzwRCkBYKISI9LUCiDCZIXguIwLgloPSggTKqXUoANYgGeJEGlIgYL0sZSIZlpBWUiHpd0cV/LZVUtIHAWASA0C2lSGQCgEAdWKD1SAUYVzuDpC6FM6sKRQhVG6BADwArSAeAcLYLwoheWkB1TcggRZZgerVaQLAGg2BImdfgQwqizDdCDXyYufAQyevpQ4EMDBnVzA8CoYgXh4gYGECIL1BBqhqGTdS5gbAQAcC4Jm7okBqWoEUNk2NSrYTCFoOW2l0rnUKt5GsPpsEXT7CjMWtMQrOwQFwIQbUoIwT0ASKgXVSILqzo7ZIMJfKBVimFaK8V6bJXdqDQqpVIAVVbs7SITYh65XHtIKq5l27SCvM6jMEAMEgA%3D%3D)

> you do not need to care about `pragma Pack` too

That's where you are wrong. The worst that happens in my case is code bloat, because all the branches still exist. The worst that happens in your case is the view window is wrong and manipulates data outside of the intended data.

> ...Mr. Randy...

He's the fucking idiot responsible for most of the problems in Ada I have to work around. I don't want to hear anything about what that mental degenerate thinks.

**Comment by ytomino** [comment]
>It's not much of a trick, as can be seen here. It's literally just selecting the correct size overlay so that the correct assembler sizes can be used. It looks far more sophisticated than it really is because of limitations in Ada. This isn't some kind of sorcery. You can see it select a different branch based on the size here

COMPILER EXPLORER seems using GNAT. It woks fine naturally.
Are we talking about the compatibility to another compiler?
If you do not admit the existence of Janus/Ada (that is a compiler), I have nothing more to say.
(Oh, I do not want to ask why you hate Randy.)

Thanks.

**Comment by Entomy** [comment]
> If you do not admit the existence of Janus/Ada (that is a compiler)

Do not put words in my mouth. Of course RR's Janus is an [existing product](http://www.rrsoftware.com/html/prodinf/janus95/j-ada95.htm). 

I think that you'd do this pretty well describes this entire interaction. You think I'm clueless and that you're some kind of mental savior who's come to help me by talking down to me the entire time. Next time maybe try just leaving it as an inquiry and not adding all the condescension.

**Comment by ytomino** [comment]
Sorry, already you probably don't talk with me. 
However I remembered  an important thing.
This is not a problem of style or incompatibility, but related to the code generation of GNAT.
Please let me leave it for when somebody see this issue later.

First, try this example:

```ada
procedure xx is
type T is (X, Y, Z);
for T use (X => 1, Y => 2, Z => 4);
for T'Size use 8;
Obj : T;
type Rep_T is mod 2 ** 8;
Rep : Rep_T;
for Rep'Address use Obj'Address;
procedure Func (Arg : T) is null;
begin
Obj := X;
Rep := 3; -- assign X or Y to Obj
Func (Obj); -- raised CONSTRAINT_ERROR : xx.adb:13 invalid data
end xx;
-- gnatmake -gnatVa xx
```

```
$ gnatmake -gnatVa xx
gcc -c -gnatVa xx.adb
gnatbind -x xx.ali
gnatlink xx.ali
$ ./xx

raised CONSTRAINT_ERROR : xx.adb:13 invalid data
```

The value not included the representation would causes the validation error with `-gnatV`.
And, the optimizer of GNAT assumes the values as valid for optimization with `-gnatB`.
http://docs.adacore.com/live/wave/gnat_ugn/html/gnat_ugn/gnat_ugn/building_executable_programs_with_gnat.html

It's same in [your example](https://github.com/Entomy/libAnne/issues/10#issuecomment-514305176). (some typo is fixed)

```ada
with Generics.Discrete_Bitwise, Ada.Text_IO;
use Generics.Discrete_Bitwise, Ada.Text_IO;

procedure Scratch is
	type File_Attribute_And_Flags is (None, Readonly, Hidden, System, Directory)
		with Size => 32;
	for File_Attribute_And_Flags use (
		None => 0,
		Readonly => 1,
		Hidden => 2,
		System => 4,
		Directory => 8);
		
	subtype Name is File_Attribute_And_Flags;
	function "not" is new Generics.Discrete_Bitwise.Discrete_Not(Name);
	function "and" is new Generics.Discrete_Bitwise.Discrete_And(Name);
	function "or" is new Generics.Discrete_Bitwise.Discrete_Or(Name);
	function "xor" is new Generics.Discrete_Bitwise.Discrete_XOr(Name);
	
	type View_Type is mod 2**32;
	
	Result : File_Attribute_And_Flags := Hidden or System; --We can now even make this constant if desired (it often is)
	View : View_Type;
	for View'Address use Result'Address;
begin
	Put_Line("Value: " & View_Type'Image(View));
end Scratch;
```

```
$ ./scratch 

raised CONSTRAINT_ERROR : generics-discrete_bitwise.adb:192 invalid data
```

This may cause some kinds of unexpected behaviors. Especially it's danger when only `-gnatB` is specified.
Even if your library is built without these options, still there is some possibility for the case that the client application is compiled with these options and inlining/LTO.

I'm terribly sorry for bothering you many times.

**Comment by Entomy** [comment]
I'm aware of this. since it's only being used in situations where the resulting value is passed directly into a C binding I decided it was acceptable. I will make sure this potential pitfall is well documented so it does not surprise others though.

**Comment by Entomy** [comment]
[29cc2055a64222b8318e458a3dde8182a85d95cc](https://github.com/Entomy/libAnne/commit/29cc2055a64222b8318e458a3dde8182a85d95cc) removes the package from the SAL Interfaces list, making it internal use only, and also adds a disclaimer about potential pitfalls as described throughout this thread.
