### ISSUE TITLE
Containers Iterator and Indexer leaks

### ISSUE THREAD

**Issue by jeremiahbreeden** [Entomy/libAnne#3]
Question on the Indexing operations for Doubly_Linked.List and similar.  I noticed that your Indexer functions are making use of Coextensions and copies of Elements rather than direct references to the elements.  Have you found that any of the recent versions of GNAT support Coextensions in this manner?  

I'm running both GNAT Community 2018 and FSF 8.2.0 and neither call Finalization, which means that everytime I iterate through an element using something like "for E of List loop" or "for C in List.Iterate loop", I get memory leaks and eventually Finalization/Adjust exceptions. 

I also noted that if I iterate through the list and assign values to the element, it doesn't actually change the elements in the list.  I can do something like:

~~~~ Ada
for E of List loop
   E.Value := Something;
end loop;

Put_Line(Something'Image);
for E of List loop
   Put_Line(E.Value'Image);
end loop;
~~~~

and the values do not reflect the value of Something.

I've only tested the libAnne lists with GNAT Community 2018 (still working on FSF GNAT as you already know).  But I ran into this before in my own libraries trying to implement coextensions.

I'll attach a compilable example main and output:

Test Main (remove .txt extension):
[main.adb.txt](https://github.com/Entomy/libAnne/files/3259716/main.adb.txt)

Output:
[test_output.txt](https://github.com/Entomy/libAnne/files/3259717/test_output.txt)

In the example you can see that each loop iteration fails to finalize the new copy.  Some, but not all finalizations happen at the end of main.  Also the value never changes to 60 like I would expect.  

Let me know if there is something I forgot to provide on this.  I went through this very quickly.

**Comment by Entomy** [comment]
Interesting, I never thought to test that. I'm not surprised by the memory leaks though. Ada's approach to iterators is absolutely bizarre to me and so I probably didn't implement it very well.

**Comment by Entomy** [comment]
> I noticed that your Indexer functions are making use of Coextensions and copies of Elements rather than direct references to the elements.

Yeah this needs to be fixed. It's not what I want to be doing at all, it was done in a "let's get it working first, then get it working well" approach, but I moved on and kept a note that it wasn't ideal behavior.

**Comment by jeremiahbreeden** [comment]
Yeah, Ada's iterator solution was tacked on too late and was designed to work around the Cursor paradigm they did in Ada95.  I feel like the Ada Cursor implementation was flawed to begin with and tacking on the Iterator one on top of it gave some more flexibility, but at the cost of sanity and readability.  GNAT's implementation of the cursor can technically "dangle" and the only way to make it non dangle that I can think of involves Controlled types, which is not very efficient.

The reference type is pretty atrocious to design correctly.  I really wish Ada provided syntax sugar, something like:

function Variable_Indexer(Self : aliased in out Container; Position : Cursor) return **aliased** Element_Type;

which would auto generate the reference type under the hood but just hide it from the user.  I would still leave in the manual way for special situations, but as a default rely on the compiler.

**Comment by Entomy** [comment]
Indexers are not required to return "Reference Types"; only the function which has no required form. This was a something I never got around to checking but I think it's possible to return a byval for "constant indexer" and a byref for "variable indexer". although for types that are always passed byref would probably have to use a `constant access`. That or I'm missing something and every constant indexer should return `constant access`.

**Comment by Entomy** [comment]
>Indexers are not required to return "Reference Types"

Whelp, Constant_Indexers aren't required to. Variable ones have to. Still though, that does optimize a huge number of cases.

**Comment by Entomy** [comment]
I've made some changes to `Singly_Linked.List` that should considerably improve behavior and fix the aforementioned issues (No more coextensions, for example). Could you check if leaks still happen for that? If no, I'll fix `Doubly_Linked.List` as well.

I also beleive NRVO can be taken advantage of for optimizing iterators a bit (at the very least, only having one cursor exist instead of creating multiple). I'll play around with this after work.

**Comment by jeremiahbreeden** [comment]
This appears to solve both my memory leak and the copying issue.  At least with the tests I have run so far.
