### ISSUE TITLE
Bindings.stdio doesn't have true constants

### ISSUE THREAD

**Issue by Entomy** [Entomy/libAnne#4]
Within [Bindings.stdio](https://github.com/Entomy/libAnne/blob/master/Common/Bindings.stdio.ads) there are declarations of `stdin`, `stdout`, and `stderr` which are conceptually constants (they are declared as macros in C) but are not able to be constants in Ada because of the way they are declared in Ada: as functions. I beleive it's quite likely that `__gnat_constant_stdin`, `__gnat_constant_stdout`, and `__gnat_constant_stderr` are unnecessarily complex and a constant value could simply be declared in C, and then imported as a constant value in Ada.

**Comment by jeremiahbreeden** [comment]
I've always been under the impression that stdin, stdout, stderr were declared as global variables.  GNAT does accept:

stdout : constant System.Address with Import, Convention => C;

I was able to use that with an fputc() binding no trouble.

**Comment by Entomy** [comment]
If it works on GNAT I'll do that. Extending to other compilers won't be too hard with the general approach I'm taking. Thanks.

**Comment by jeremiahbreeden** [comment]
Here is a quick test package I did in a couple different versions of GNAT:

~~~~Ada

with Ada.Text_IO; use Ada.Text_IO;
with System;
with Interfaces.C;

procedure Hello is


    package Bindings is
       
        stdout : constant System.Address with Import, Convention => C;
        subtype int is Interfaces.C.int;
       
        function fputc(Value : int; Stream : System.Address) return int
            with Import, Convention => C;
    
    end Bindings;
    
    procedure Put_Character(C : Character) is
        use Bindings;
        
        Result : int := fputc(Character'Pos(C),stdout);
    begin
        null;
    end;
    
    Test : String := "Thank You";
    
begin
    Put_Line("Hello, world!");
  
    for C of Test loop
        Put_Character(C);
    end loop;
    
    New_Line;
  
end Hello;

~~~~

**Comment by Entomy** [comment]
This won't work when linking against Microsoft's libC and likely others.

![image](https://user-images.githubusercontent.com/25399505/59077144-46c8ee00-88a7-11e9-8c76-08c5c6c39c30.png)

So I'll have to writing code that creates a constant which can be imported, then import that.

**Comment by jeremiahbreeden** [comment]
Well that stinks.   It was worth a shot.

**Comment by Entomy** [comment]
Given my admittedly limited knowledge of C, I don't beleive this is possible. I know a simple `const FILE *` isn't doable at all because on certain platforms the macro expands to a function call, like with Windows and `__acrt_iob_func()`. `constexpr` may be able to handle this, however it's a C++ feature not a C feature, so bindings against C++ would be required, which is generally not feasible.

**Comment by Entomy** [comment]
And... no `constexpr` can not handle this either, because it requires the calling function, in Windows case: `__acrt_iob_func()` to also be either `const` or `constexpr`, which it's not.

**Comment by jeremiahbreeden** [comment]
Yeah, constexpr is really useful for embedded stuff, but isn't flexible enough yet.  I know you mentioned not liking the gnat internals, but how opposed are you using them with deferred constants?

````Ada
   package Bindings is
    
        stdin : constant System.Address;
        
        -- other stuff
        
    private 
        
        function Gnat_Standard_In return System.Address
            with Import, 
                 Convention    => C, 
                 External_Name => "__gnat_constant_stdin";
                 
        stdin : constant System.Address := Gnat_Standard_In;
    
    end Bindings;
````

or potentially:

libanne_stdio.c
````C
#include <stdio.h>
FILE * libanne_stdin(void){ return stdin; }
// others
````

paired with 

````Ada
   package Bindings is
    
        stdin : constant System.Address;
        
        -- other stuff
        
    private 
        
        function libanne_stdin return System.Address
            with Import, 
                 Convention    => C;
                 
        stdin : constant System.Address := libanne_stdin;
    
    end Bindings;
````

Not super ideal I know, but trying to come up with something that will be portable enough for ya and not too terrible.  The first option doesn't require the extra C file but only works with the GNAT compiler (or will this also interfere with you linking to Microsoft's libC?  I don't have a way to test that).  The second way does require the extra C file, but *should* work with any stdio.h?

**Comment by jeremiahbreeden** [comment]
If you don't want them constant (say if you want to be able to change them, you can do something like:

````Ada
   package Bindings is
    
        stdin : System.Address 
        with Import, 
             Convention => C, 
             External_Name => "libanne_stdin_var";
        
        -- other stuff
        
    private
        
        function Gnat_Standard_In return System.Address
            with Import, 
                 Convention    => C, 
                 External_Name => "__gnat_constant_stdin";
                 
        libanne_stdin_var : System.Address := Gnat_Standard_In
        with Export,
             Convention => C;
    
    end Bindings;
````

That's a bit over complicated but just trying to keep the spec looking clean.  You could obviously just import the __gnat_constant_stdin in the public part if you think the other stuff is too crazy:

````Ada
   package Bindings is
    
        function Default_stdin return System.Address
            with Import, 
                 Convention    => C, 
                 External_Name => "__gnat_constant_stdin";
    
        stdin : System.Address := Default_stdin;
        
        -- other stuff
    
    end Bindings;
````

**Comment by Entomy** [comment]
@jeremiahbreeden I'm actually trying to have it to where the stdio streams can't be changed, since it would allow redirecting `Console` which creates very confusing results and will result in ANSI escapes on some platforms, and unrelated and ineffectual function calls on others. So constants are preferred.

**Comment by jeremiahbreeden** [comment]
Understandable!  Will one of the deferred constant versions from the post above that one work ok for you potentially?

**Comment by Entomy** [comment]
I got to test one of them, I'll do it in the morning though, since I had a stupidly busy night at work.


On June 15, 2019, at 21:54, Jere <notifications@github.com> wrote:


Understandable! Will one of the deferred constant versions from the post above that one work ok for you potentially?

**Comment by Entomy** [comment]
Boy that'll be the last time I use an email response.

Anyways, @jeremiahbreeden you can always issue a pull request as well. I have no intention of excluding others, nor their ideas. 😉
