### ISSUE TITLE
Build failed on Ubuntu 18.04 using AdaCore Community 2019

### ISSUE THREAD

**Issue by freeark1** [Entomy/libAnne#9]
Hardware: x86_64
OS: Ubuntu 18.04 Desktop
gnat: AdaCore Community 2019

ran : gprbuild -P libAnne.gpr -p -XPlatform=UNIX

Output:
Setup
   [mkdir]        object directory for project Core
   [mkdir]        library directory for project Core
Compile
   [Ada]          Doubly_Linked_List_Tests.adb
   [Ada]          Filesystem_Tests.adb
   [Ada]          Singly_Linked_List_Tests.adb
   [Ada]          stdio_Tests.adb
   [Ada]          stdlib_Tests.adb
   [Ada]          Text_Tests.adb
   [Ada]          wchar_Tests.adb
   [Ada]          Ada_Text_IO_Profile.adb
   [Ada]          Console_Profile.adb
   [Ada]          Singly_Linked_List_Profile.adb
   [C]            anne_stdio.c
   [C]            anne_stdlib.c
   [C]            anne_wchar.c
   [C]            anne_stdbool.c
   [C]            anne_limits.c
   [C]            anne_errno.c
   [Ada]          Console.adb
   [Ada]          Mathematics.Matrices.adb
   [Ada]          Generics.Text.Handling.adb
   [Ada]          Containers.ads
   [Ada]          Generics.Testing.Assertions.adb
   [Ada]          Containers.Buffers.Ring.adb
   [Ada]          Colors.ads
   [Ada]          Generics.Testing.Discrete_Assertions.adb
   [Ada]          Bindings.stdbool.ads
Bindings.stdbool.ads:9:58: warning: return type of "anne_bool_true_false_are_defined" is an 8-bit Ada Boolean
Bindings.stdbool.ads:9:58: warning: use appropriate corresponding type in C (e.g. char)
   [Ada]          Generics.Testing.Decimal_Assertions.adb
   [Ada]          Generics.Mathematics.Angles.adb
   [Ada]          Containers.Float_Stacks.adb
   [Ada]          Mathematics.Percents.ads
   [Ada]          Bindings.ads
   [Ada]          Colors.Models.Grayscale.adb
   [Ada]          Numerics.ads
   [Ada]          Generics.Mathematics.adb
   [Ada]          Generics.Numerics.adb
   [Ada]          Generics.Testing.Float_Assertions.adb
   [Ada]          Generics.Testing.ads
   [Ada]          Generics.Mathematics.Matrices.adb
   [Ada]          Generics.Text.adb
   [Ada]          Text.Handling.adb
   [Ada]          Mathematics.adb
   [Ada]          Colors.Html.ads
   [Ada]          Testing.Assertions.adb
   [Ada]          Generics.Containers.Lists.ads
   [Ada]          Containers.Lists.ads
   [Ada]          Generics.Testing.Definite_Assertions.adb
   [Ada]          Containers.Lists.Singly_Linked.adb
   [Ada]          Bindings.errno.ads
   [Ada]          Containers.Decimal_Stacks.adb
   [Ada]          Containers.Priority_Queues.adb
   [Ada]          Text.adb
   [Ada]          Generics.Mathematics.Arrays.adb
   [Ada]          Containers.Modular_Stacks.adb
   [Ada]          Containers.Fixed_Stacks.adb
   [Ada]          Testing.Timers.adb
   [Ada]          Generics.Arrays.adb
   [Ada]          Bindings.stdio.ads
   [Ada]          Containers.Buffers.ads
   [Ada]          Bindings.limits.ads
   [Ada]          Mathematics.Angles.adb
   [Ada]          Colors.Models.Red_Green_Blue.adb
   [Ada]          Containers.Queues.adb
   [Ada]          Containers.Stacks.adb
   [Ada]          Containers.Lists.Doubly_Linked.adb
   [Ada]          Bindings.wchar.ads
   [Ada]          Generics.Containers.ads
   [Ada]          Bindings.stdlib.ads
   [Ada]          Generics.Mathematics.Percents.adb
   [Ada]          Testing.ads
   [Ada]          Filesystem.ads
cannot generate code for file Filesystem.ads (package spec)
gprbuild: *** compilation phase failed

**Comment by Entomy** [comment]
This isn't a failed build as much as you're trying to build a commit that is incomplete. Feature #6 hasn't been implemented yet. You can try deleting the `Filesystem.ads` file from `Common` and see what happens from there.
